### PR TITLE
python-debian 0.1.49, add maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- includes #4

Changes:
- [x] update metadata
- [x] use canonical upstream for `gpl-2.0`
- [x] update `pip` invocation 
- [x] add maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/python-debian ready for review

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/python-debian ready for review

@conda-forge/core this has been sitting unreviewed for many months now

**Comment by ocefpaf** [comment]
@mbargull, hope you don't mind me merging this one.

**Comment by bollwyvl** [comment]
Thank you!

**Pull request merged**
